### ISSUE TITLE
Objetivo 4 con yarn

### ISSUE THREAD

**Issue by carlotiii30** [JJ/IV-#154]
Al pasar los tests te obliga a que ponga ```yarn run``` para el chequeo de la sintaxis y para los tests, cuando en realidad esto no es necesario, si no que se pueden utilizar las ordenes ```yarn check``` y ```yarn test```.

**Comment by JJ** [comment]
Entonces el prefijo sería solamente `yarn`, no `yarn run`. Los tests buscan en el README el prefijo que tú hayas puesto en el fichero `iv.yaml`

**Comment by carlotiii30** [comment]
Tiene razón, perdón, pensaba que lo tenía puesto solo con ```yarn```.
